--請求データ状況テーブル作成
create table if not exists T_BILLING_STATUS(
billing_ym DATE PRIMARY KEY,
is_commited BOOLEAN DEFAULT false NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL);

--請求データテーブル作成
create table if not exists T_BILLING_DATA(
billing_ym DATE NOT NULL REFERENCES T_BILLING_STATUS(billing_ym),
member_id INTEGER NOT NULL,
mail VARCHAR(256) NOT NULL,
name VARCHAR(32) NOT NULL,
address VARCHAR(128) NOT NULL,
start_date DATE NOT NULL,
end_date DATE,
payment_method INTEGER NOT NULL,
amount NUMBER(10,0) NOT NULL,
tax_ratio NUMBER(5,2) NOT NULL,
total NUMBER(10,0) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY(billing_ym,member_id));

--請求明細データ作成
create table if not exists T_BILLING_DETAIL_DATA(
billing_ym DATE NOT NULL,
member_id INTEGER NOT NULL,
charge_id INTEGER NOT NULL,
name VARCHAR(64) NOT NULL,
amount NUMERIC(10,1) NOT NULL,
start_date DATE NOT NULL,
end_date DATE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY (billing_ym, member_id, charge_id),
FOREIGN KEY (billing_ym, member_id)
REFERENCES T_BILLING_DATA(billing_ym, member_id));